project:
  type: website
  output-dir: docs
website:
  title: "Blog"
  description: "Statistics, R Programming, and Data Analysis"
  navbar:
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/sl-eeper
        aria-label: "GitHub Profile"
format:
  html:
    smooth-scroll: true
    theme: flatly
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: false
    citeproc: true
    reference-location: document
    footnotes-hover: true
    icon-pack: bootstrap
editor: visual

