project:
  type: website
  output-dir: docs
website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sl-eeper
format:
  html:
    smooth-scroll: true
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: false
    citeproc: true
    reference-location: document
    footnotes-hover: true
    icon-pack: bootstrap
editor: visual

