project:
  type: website
  output-dir: docs
website:
  title: "blog"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: true
    citeproc: true
    reference-location: document
    footnotes-hover: true

editor: visual

