<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hyungwoo Jo">
<meta name="dcterms.date" content="2025-06-27">
<meta name="description" content="의학 연구에서의 인과추론: 기본 개념">

<title>Causal Inference (1) – Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e618cfa586025e0e0628123d03262de7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sl-eeper"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Causal Inference (1)</h1>
                  <div>
        <div class="description">
          의학 연구에서의 인과추론: 기본 개념
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">statistics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://github.com/hyungwoo-jo">Hyungwoo Jo</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 27, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#서론" id="toc-서론" class="nav-link active" data-scroll-target="#서론">서론</a></li>
  <li><a href="#인과추론의-근본적인-문제-the-fundamental-problem-of-causal-inference" id="toc-인과추론의-근본적인-문제-the-fundamental-problem-of-causal-inference" class="nav-link" data-scroll-target="#인과추론의-근본적인-문제-the-fundamental-problem-of-causal-inference">1. 인과추론의 근본적인 문제 (The Fundamental Problem of Causal Inference)</a></li>
  <li><a href="#무작위-배정-임상시험-rct과-교환가능성" id="toc-무작위-배정-임상시험-rct과-교환가능성" class="nav-link" data-scroll-target="#무작위-배정-임상시험-rct과-교환가능성">2. 무작위 배정 임상시험 (RCT)과 교환가능성</a>
  <ul class="collapse">
  <li><a href="#무작위-배정과-평균-인과-효과-추정" id="toc-무작위-배정과-평균-인과-효과-추정" class="nav-link" data-scroll-target="#무작위-배정과-평균-인과-효과-추정">무작위 배정과 평균 인과 효과 추정</a></li>
  <li><a href="#교환가능성-exchangeability-rct의-핵심-가정" id="toc-교환가능성-exchangeability-rct의-핵심-가정" class="nav-link" data-scroll-target="#교환가능성-exchangeability-rct의-핵심-가정">교환가능성 (Exchangeability): RCT의 핵심 가정</a></li>
  </ul></li>
  <li><a href="#관찰-연구와-조건부-교환가능성" id="toc-관찰-연구와-조건부-교환가능성" class="nav-link" data-scroll-target="#관찰-연구와-조건부-교환가능성">3. 관찰 연구와 조건부 교환가능성</a>
  <ul class="collapse">
  <li><a href="#r-예제-코드-교란-효과-시뮬레이션" id="toc-r-예제-코드-교란-효과-시뮬레이션" class="nav-link" data-scroll-target="#r-예제-코드-교란-효과-시뮬레이션">R 예제 코드: 교란 효과 시뮬레이션</a></li>
  </ul></li>
  <li><a href="#미측정-교란변수의-한계" id="toc-미측정-교란변수의-한계" class="nav-link" data-scroll-target="#미측정-교란변수의-한계">4. 미측정 교란변수의 한계</a></li>
  <li><a href="#시간축관련-편향-time-related-biases" id="toc-시간축관련-편향-time-related-biases" class="nav-link" data-scroll-target="#시간축관련-편향-time-related-biases">5. 시간축관련 편향 (Time-related Biases)</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="서론" class="level2">
<h2 class="anchored" data-anchor-id="서론">서론</h2>
<p>본 문서는 Real-World Data(RWD)를 활용한 인과추론(Causal Inference)의 핵심 개념을 다룬다. 의학 연구의 목표 중 하나는 특정 개입(intervention)이 결과(outcome)에 미치는 인과적 효과(causal effect)를 규명하는 것이다. 본 글에서는 인과추론의 근본적인 문제와, 이를 해결하기 위한 무작위 배정 임상시험(RCT), 그리고 관찰 연구(observational study)에서의 접근법을 순차적으로 소개한다.</p>
<hr>
</section>
<section id="인과추론의-근본적인-문제-the-fundamental-problem-of-causal-inference" class="level2">
<h2 class="anchored" data-anchor-id="인과추론의-근본적인-문제-the-fundamental-problem-of-causal-inference">1. 인과추론의 근본적인 문제 (The Fundamental Problem of Causal Inference)</h2>
<p>임상 현장에서는 특정 질환에 대해 여러 치료 대안이 존재할 때, 어떤 치료법이 더 나은 예후를 가져오는지 판단해야 하는 문제에 직면한다. 예를 들어, 특정 암으로 진단된 65세 남성 환자 ‘A’씨가 있고, 치료법으로 ’수술’과 ’약물치료’가 고려되고 있다고 가정해 보자. 이 연구에서 관심 있는 최종 결과는 ’1년 후 생존 여부’(생존 시 1, 사망 시 0)이다.</p>
<p>인과추론의 핵심 개념인 잠재적 결과 프레임워크(Potential Outcomes Framework)는 이 상황을 다음과 같이 설명한다. A씨에게는 우리가 관찰할 수는 없지만 개념적으로 존재하는 두 가지의 잠재적 결과가 있다.</p>
<ul>
<li><span class="math inline">\(Y_{A}(1)\)</span>: A씨가 ’수술’을 받았을 경우의 1년 후 생존 상태</li>
<li><span class="math inline">\(Y_{A}(0)\)</span>: A씨가 ’약물치료’를 받았을 경우의 1년 후 생존 상태</li>
</ul>
<p>만약 우리가 신처럼 모든 가능성을 알 수 있어, A씨가 수술을 받으면 1년 후 생존하고(<span class="math inline">\(Y_{A}(1)=1\)</span>), 약물치료를 받으면 1년 후 사망한다(<span class="math inline">\(Y_{A}(0)=0\)</span>)는 사실을 안다고 상상해 보자. 이때 A씨 개인에 대한 수술의 인과적 효과는 <span class="math inline">\(Y_{A}(1) - Y_{A}(0) = 1 - 0 = 1\)</span>로 명확하게 계산된다. 이 차이값, 즉 <strong>한 개인에 대한 잠재적 결과들의 차이가 바로 우리가 궁극적으로 알고자 하는 ‘진정한 인과적 효과(true causal effect)’</strong>이다. 이는 해당 치료가 그 개인에게 미친 순수한 영향의 크기를 의미한다.</p>
<p>그러나 현실 세계에서 A씨는 두 가지 치료 중 단 하나만 받을 수 있다. 만약 그가 실제로 수술을 선택하여 1년 후 생존했다면, 우리는 <span class="math inline">\(Y_{A}(1)=1\)</span>이라는 ‘사실적(factual)’ 결과만을 관찰할 수 있다. 그가 만약 약물치료를 받았더라면 어땠을지에 대한 결과, 즉 <span class="math inline">\(Y_{A}(0)\)</span>의 값은 영원히 관찰 불가능한 ’반사실적 사실(Counterfactual)’로 남게 된다.</p>
<p>이처럼 동일한 개인에 대해 모든 잠재적 결과를 동시에 관찰하는 것이 원천적으로 불가능하다는 점, 이것이 바로 <strong>‘인과추론의 근본적인 문제(The Fundamental Problem of Causal Inference)’</strong>이다.</p>
<hr>
</section>
<section id="무작위-배정-임상시험-rct과-교환가능성" class="level2">
<h2 class="anchored" data-anchor-id="무작위-배정-임상시험-rct과-교환가능성">2. 무작위 배정 임상시험 (RCT)과 교환가능성</h2>
<p>앞에서 살펴본 ‘A씨’ 개인에 대한 수술의 인과적 효과(<span class="math inline">\(Y_{A}(1) - Y_{A}(0)\)</span>)를 아는 것은 <strong>‘인과추론의 근본적인 문제’</strong>로 인해 불가능하다. 그렇다면 연구자로서 우리는 어떤 의미 있는 질문을 던질 수 있을까? 바로 “A씨 한 명이 아니라, A씨와 유사한 특성을 가진 환자 집단 전체에서 수술은 약물치료에 비해 평균적으로 얼마나 효과적인가?”라는 질문이다. 이처럼 목표를 개인에서 집단으로 수정하여, 특정 인구 집단 전체에 대한 <strong>’평균 인과 효과(Average Causal Effect, ACE 또는 Average Treatment Effect, ATE)</strong>를 추정하는 것으로 전환한다.</p>
<p>이 개념을 이해하기 위해, 해당 질환을 가진 환자가 10명(A부터 J까지)뿐인 가상의 인구 집단을 상상해 보자. 신의 관점에서 이들 각각의 잠재적 결과를 모두 알고 있다고 가정하면 아래 표와 같다. (생존=1, 사망=0)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">환자</th>
<th style="text-align: center;">수술 시 생존 여부 <span class="math inline">\(Y(1)\)</span></th>
<th style="text-align: center;">약물치료 시 생존 여부 <span class="math inline">\(Y(0)\)</span></th>
<th style="text-align: center;">개인의 인과 효과 <span class="math inline">\(Y(1) - Y(0)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">J</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<p>위 표에서 각 개인에 대한 치료의 인과 효과는 이질적(heterogeneous)이다. A, D, E, H, J 환자에게 수술은 생존을 결정짓는 긍정적 효과(+1)를 가진다. B와 F 환자에게는 두 치료법 모두 효과가 있어 차이가 없고(0), C와 I 환자에게는 두 치료법 모두 효과가 없어 역시 차이가 없다(0). 특히 G 환자의 경우, 오히려 약물치료가 더 나은 결과를 보여 수술의 효과는 부정적(-1)이다. <strong>현실에서는 이 마지막 열, 즉 개인별 효과를 결코 알 수 없다.</strong></p>
<p><strong>평균 인과 효과(ACE)</strong>는 바로 이 마지막 열에 있는 개인별 인과 효과들의 평균이다. <span class="math display">\[\text{ACE} = \frac{1+0+0+1+1+0+(-1)+1+0+1}{10} = \frac{4}{10} = 0.4\]</span> 이 값 <span class="math inline">\(0.4\)</span>는 이 인구 집단에서 약물치료 대신 수술을 선택할 경우, 생존할 확률이 <strong>평균적으로</strong> <span class="math inline">\(0.4\)</span> (또는 <span class="math inline">\(40\%\)</span>p) 증가함을 의미한다. 이는 G 환자처럼 일부에게는 수술이 해가 되더라도, 집단 전체적으로는 수술이 더 이득이 됨을 보여주는 중요한 정보다.</p>
<p>이처럼 개인 수준의 효과는 알 수 없지만, 연구자들은 집단 수준의 평균적인 효과를 추정함으로써 치료법의 가치를 평가하고 임상적 의사결정에 대한 과학적 근거를 제공할 수 있다. 앞선 예시에서 우리가 신의 관점으로 계산한 ‘진정한’ 평균 인과 효과(ACE)는 <span class="math inline">\(0.4\)</span>였다. 이제 현실의 연구자가 이 값을 어떻게 추정해 나가는지 살펴본다.</p>
<hr>
<section id="무작위-배정과-평균-인과-효과-추정" class="level3">
<h3 class="anchored" data-anchor-id="무작위-배정과-평균-인과-효과-추정">무작위 배정과 평균 인과 효과 추정</h3>
<p>이 평균 인과 효과를 가장 신뢰도 높게 추정하기 위한 연구 설계가 바로 <strong>무작위 배정 임상시험(Randomized Controlled Trial, RCT)</strong>이다. RCT의 핵심은 <strong>무작위 배정(randomization)</strong>에 있다. 앞선 10명의 환자(A~J)를 동전 던지기와 같은 확률적 과정에 따라 5명은 수술군(Treatment, <span class="math inline">\(T=1\)</span>)에, 나머지 5명은 약물치료군(Control, <span class="math inline">\(T=0\)</span>)에 배정한다고 가정해 보자.</p>
<p>무작위 배정은 매우 강력한 도구로, 각 환자가 어떤 치료를 받을지 <strong>오직 우연에 의해서만 결정</strong>되도록 한다. 만약 대상자 수가 충분히 많다면, 무작위 배정은 치료군과 대조군이 치료와 무관한 모든 특성(나이, 성별, 기저 질환의 중증도, 생활 습관 등)에서 <strong>평균적으로 거의 동일하게 분포</strong>되도록 만든다. 이는 마치 두 집단이 <strong>‘복제된(counterfactual) 상태’</strong>와 같이 되는 것을 의미한다.</p>
<p>여기서는 10명이라는 소규모 집단이지만, 무작위 배정이 성공적으로 이루어져 두 그룹의 기저 특성이 잘 균형을 이루었다고 가정해 보자. 예를 들어, 한 가지 무작위 배정 결과가 아래와 같이 나왔다고 하자.</p>
<ul>
<li><strong>수술군 (</strong><span class="math inline">\(T=1\)</span>): {A, D, E, H, J}</li>
<li><strong>약물치료군 (</strong><span class="math inline">\(T=0\)</span>): {B, C, F, G, I}</li>
</ul>
<p>연구자는 이제 신의 관점이 아닌, 실제 관찰된 데이터만을 볼 수 있다. 즉, 수술군에 속한 환자에게서는 수술 후의 결과(<span class="math inline">\(Y(1)\)</span>)만을, 약물치료군에 속한 환자에게서는 약물치료 후의 결과(<span class="math inline">\(Y(0)\)</span>)만을 관찰하게 된다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">환자</th>
<th style="text-align: center;">배정된 군 (T)</th>
<th style="text-align: center;">실제 관찰된 결과 (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">1 (수술)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{A}(1)=1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">0 (약물)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{B}(0)=1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: center;">0 (약물)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{C}(0)=0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: center;">1 (수술)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{D}(1)=1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">1 (수술)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{E}(1)=1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">0 (약물)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{F}(0)=1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">0 (약물)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{G}(0)=1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">1 (수술)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{H}(1)=1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: center;">0 (약물)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{I}(0)=0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">J</td>
<td style="text-align: center;">1 (수술)</td>
<td style="text-align: center;"><span class="math inline">\(Y_{J}(1)=1\)</span></td>
</tr>
</tbody>
</table>
<p>이 관찰된 데이터를 바탕으로 연구자는 각 그룹의 평균 결과를 계산한다.</p>
<ul>
<li>관찰된 수술군의 평균 생존율: <span class="math inline">\(E[Y|T=1] = (1+1+1+1+1)/5 = 1.0\)</span></li>
<li>관찰된 약물치료군의 평균 생존율: <span class="math inline">\(E[Y|T=0] = (1+0+1+1+0)/5 = 0.6\)</span></li>
<li>관찰된 결과의 차이: <span class="math inline">\(1.0 - 0.6 = 0.4\)</span></li>
</ul>
<p>이 값(<span class="math inline">\(0.4\)</span>)은 우리가 앞에서 신의 관점으로 계산했던 <strong>실제 ACE(</strong><span class="math inline">\(0.4\)</span>)와 정확히 일치한다. 10명이라는 작은 표본에서도 무작위 배정이 성공적으로 이루어진다면 이렇게 실제 평균 인과 효과를 잘 추정할 수 있다. 물론 실제 임상 연구에서는 무작위 오차(Random Error)를 줄이기 위해 훨씬 더 많은 수의 환자를 대상으로 연구를 수행하며, 이러한 과정을 통해 관찰된 차이는 ‘진정한’ 평균 인과 효과에 더욱 가깝게 수렴하게 된다.</p>
<hr>
</section>
<section id="교환가능성-exchangeability-rct의-핵심-가정" class="level3">
<h3 class="anchored" data-anchor-id="교환가능성-exchangeability-rct의-핵심-가정">교환가능성 (Exchangeability): RCT의 핵심 가정</h3>
<p>이것이 가능한 근본적인 원리가 바로 <strong>교환가능성(Exchangeability)</strong>이다. 무작위 배정은 두 집단의 모든 특성을 평균적으로 동일하게 만들어, 치료 개입이 시작되기 전 시점에서 두 집단을 통계적으로 거의 복제된 상태로 만든다. ’교환가능성’은 기호를 통해 더 깊이 이해할 수 있다. 무작위 배정 덕분에 우리는 치료군과 대조군의 잠재적 결과가 다음과 같은 관계를 가진다고 가정할 수 있다.</p>
<p>우리가 앞서 본 10명의 환자 예시를 다시 떠올려 보자. 이 환자들을 두 그룹으로 나눌 때, <strong>난수표</strong>를 이용해 짝수 번호가 나온 환자는 수술군에, 홀수 번호가 나온 환자는 약물치료군에 배정하는 것과 같다. 이렇게 무작위로 배정하면, 마치 신의 관점에서 보았을 때 두 그룹이 완벽하게 균형을 이루게 된다.</p>
<p>예를 들어, 난수표를 통해 짝수 번호를 받아 <strong>수술군에 배정된 환자 5명(A, D, E, H, J)</strong>이 실제로 수술을 받았을 때 5명 모두 생존하여 생존율이 100%(<span class="math inline">\(1.0\)</span>)가 나왔다고 가정해 보자. 그리고 홀수 번호를 받아 <strong>약물치료군에 배정된 환자 5명(B, C, F, G, I)</strong>이 실제로 약물치료를 받았을 때 3명이 생존하여 생존율이 60%(<span class="math inline">\(0.6\)</span>)가 나왔다고 가정해 보자. 관찰된 결과의 차이는 <span class="math inline">\(1.0 - 0.6 = 0.4\)</span>이다.</p>
<p>여기서 핵심은 <strong>’만약’이라는 반사실적 상황</strong>이다. 교환가능성은 다음과 같이 설명한다.</p>
<ul>
<li><p><strong>수술군에 배정된 짝수 그룹(A, D, E, H, J)이 만약 약물치료를 받았다면 어땠을까(</strong><span class="math inline">\(E[Y(0) | T=1]\)</span>)? 무작위 배정 덕분에, 이 짝수 그룹의 잠재적 약물치료 결과는 <strong>실제로 약물치료를 받은 홀수 그룹(B, C, F, G, I)의 결과(</strong><span class="math inline">\(E[Y(0) | T=0]\)</span>)와 평균적으로 동일할 것이라고 가정할 수 있다. 즉, 짝수 그룹이 약물치료를 받았어도 홀수 그룹과 마찬가지로 5명 중 3명이 생존하여 평균 생존율이 60%(<span class="math inline">\(0.6\)</span>)였을 것이라는 뜻이다.</p></li>
<li><p><span class="math inline">\(E[Y(0) | T=1] = E[Y(0) | T=0]\)</span></p>
<ul>
<li>좌변 <span class="math inline">\(E[Y(0) | T=1]\)</span>은 <strong>수술군(</strong><span class="math inline">\(T=1\)</span>)이 만약 약물치료를 받았다면 어땠을까(<span class="math inline">\(Y(0)\)</span>)에 대한 평균 결과를 의미한다. 이는 수술군의 관찰 불가능한 ’반사실’이다.</li>
<li>우변 <span class="math inline">\(E[Y(0) | T=0]\)</span>은 <strong>실제로 약물치료군(</strong><span class="math inline">\(T=0\)</span>)에서 관찰된 평균 결과이다.</li>
<li>즉, ’교환가능성’이란 수술군의 반사실적 결과(만약 약물치료를 받았다면 어땠을지)가 약물치료군의 사실적 결과와 같을 것이라는 강력한 가정이며, 이는 오직 무작위 배정에 의해서만 정당화될 수 있다.</li>
</ul></li>
</ul>
<p>더 나아가, 교환가능성은 치료 배정 여부(<span class="math inline">\(T\)</span>)와 잠재적 결과(<span class="math inline">\(Y(1), Y(0)\)</span>)가 서로 독립적이라는 것을 의미하며, 이를 통계적 기호로 나타내면 다음과 같다.</p>
<p><span class="math display">\[(Y(1), Y(0)) \perp T\]</span></p>
<p>이 독립성(교환가능성) 가정 덕분에 우리는 관찰 불가능한 평균 인과 효과를 관찰 가능한 데이터로 추정할 수 있게 된다. 그 수학적 원리는 다음과 같다.</p>
<ol type="1">
<li>우리가 추정하고자 하는 목표는 <strong>ACE</strong> = <span class="math inline">\(E[Y(1) - Y(0)]\)</span> 이다.</li>
<li>기댓값의 선형성에 따라, 이는 <span class="math inline">\(E[Y(1)] - E[Y(0)]\)</span> 와 같다.</li>
<li><strong>무작위 배정(예: 난수표를 통한 짝수/홀수 배정)</strong>으로 인해 치료 배정 여부(<span class="math inline">\(T\)</span>)와 잠재적 결과(<span class="math inline">\(Y(1), Y(0)\)</span>)는 서로 독립적이 된다. 즉, <strong>교환가능성</strong>이 성립한다: <span class="math inline">\((Y(1), Y(0)) \perp T\)</span></li>
<li>이 독립성(교환가능성) 가정 덕분에, 우리는 잠재적 결과의 평균을 특정 집단에서 관찰된 결과의 평균으로 대체할 수 있다.
<ul>
<li><span class="math inline">\(E[Y(1)] = E[Y(1)|T=1] = E[Y|T=1]\)</span> (수술의 평균 잠재 효과는 수술군에서 관찰된 평균과 같다)</li>
<li><span class="math inline">\(E[Y(0)] = E[Y(0)|T=0] = E[Y|T=0]\)</span> (약물의 평균 잠재 효과는 약물군에서 관찰된 평균과 같다)</li>
</ul></li>
<li>따라서, 관찰이 불가능했던 목표치 <span class="math inline">\(E[Y(1)] - E[Y(0)]\)</span>는 관찰 가능한 두 집단의 평균 결과 차이, 즉 <span class="math inline">\(E[Y|T=1] - E[Y|T=0]\)</span> 로 계산될 수 있다.</li>
</ol>
<p>결론적으로, RCT를 통해 계산한 치료군과 대조군의 단순한 평균 결과 차이는 ’평균 인과 효과’의 편향되지 않은(unbiased) 추정치가 된다. 이처럼 RCT는 무작위 배정이라는 강력한 장치를 통해 측정되거나 측정되지 않은 모든 교란변수 문제를 원천적으로 해결하고 인과성을 명확하게 규명해주기 때문에, 인과추론 연구의 <strong>‘황금 표준(Gold Standard)’</strong>으로 간주된다.W</p>
</section>
</section>
<section id="관찰-연구와-조건부-교환가능성" class="level2">
<h2 class="anchored" data-anchor-id="관찰-연구와-조건부-교환가능성">3. 관찰 연구와 조건부 교환가능성</h2>
<p>앞서 RCT가 인과추론의 ’황금 표준’임을 확인했다. 하지만 모든 임상적 질문에 RCT를 적용하는 것은 현실적으로 불가능하거나 바람직하지 않을 때가 많다. <strong>윤리적 문제</strong>로 인해 효과가 입증된 치료를 환자에게 제공하지 않거나, 반대로 위험할 수 있는 시술에 무작위 배정할 수 없다. 수백, 수천억에 달하는 <strong>막대한 비용과 수년에 걸친 시간</strong>은 희귀 질환이나 장기적인 효과를 연구하는 데 큰 장벽이 된다. 또한, RCT는 참여 조건이 까다로워 실제 진료 현장의 다양하고 복잡한 환자군을 대표하지 못해 <strong>결과의 일반화 가능성이 떨어지는</strong> 한계도 있다.</p>
<p>이러한 이유들로 인해, 연구자들은 실제 진료 환경에서 자연스럽게 축적된 방대한 데이터, 즉 <strong>RWD(Real-World Data)를 활용한 관찰 연구</strong>에 눈을 돌리게 된다. 하지만 이와 동시에 우리는 RCT의 강력한 무기였던 ’무작위 배정’을 포기해야만 하며, 이는 <strong>선택 편향(selection bias)</strong>으로 인한 <strong>교란(confounding)</strong>이라는 새로운 문제에 직면하게 만든다.</p>
<p>관찰 연구에서 치료법의 선택은 연구자의 개입 없이 환자 및 임상의의 특성에 따라 자연스럽게 결정된다. 예를 들어, 특정 질환에 대해 고령의 환자는 수술의 위험 부담으로 인해 약물치료를, 상대적으로 건강한 젊은 환자는 수술을 선택하는 경향이 있을 수 있다. 이 경우, ’수술군’은 평균 연령이 낮고, ’약물치료군’은 평균 연령이 높은 두 집단이 만들어진다.</p>
<p>여기서 ’나이’는 치료법 선택(고령일수록 약물치료 선호)과 결과(고령일수록 사망 위험 높음) 모두에 영향을 미치므로 <strong>교란변수(confounder)</strong>로 작용한다. 만약 두 그룹의 사망률을 단순 비교한다면, 약물치료 그룹의 사망률이 더 높게 나타날 것이다. 하지만 이 결과는 약물치료가 덜 효과적이라서가 아니라, 단지 약물치료 그룹에 나이가 많아 사망 위험이 원래 높았던 환자들이 몰려있기 때문에 발생하는 편향일 수 있다. 즉, 치료법의 효과와 나이의 효과가 뒤섞여 나타나는 것이다.</p>
<p>RCT와 달리 관찰 연구에서는 치료군과 대조군이 비교 가능하지 않은, 즉 <strong>교환가능하지 않은(non-exchangeable)</strong> 상태에서 출발한다. 이처럼 ’나이’라는 교란변수 때문에 발생하는 편향을 극복하고 공정한 비교를 하기 위해, 우리는 <strong>조건부 교환가능성(Conditional Exchangeability)</strong>이라는 핵심적인 가정을 만족시켜야 한다.</p>
<p>조건부 교환가능성이란, <strong>‘비교를 왜곡하는 교란변수(X)의 값을 동일하게 고정하고 그 조건 안을 들여다보면, 두 그룹이 비로소 공정하게 비교 가능해진다’</strong>는 핵심 아이디어이다.</p>
<p>가장 직관적인 예시는 ‘나이’를 기준으로 생각해보는 것이다. 전체 환자를 비교하는 대신, <strong>오직 75세 환자들만</strong>을 모아 그 안에서 수술받은 사람과 약물치료받은 사람의 결과를 비교한다면, 적어도 ’나이’로 인한 편향은 사라진다. 이 ’나이(<span class="math inline">\(X\)</span>)를 75세로 고정하는(<span class="math inline">\(\mid X=75\)</span>)’ 조건 하에서는 치료 선택(<span class="math inline">\(T\)</span>)이 환자의 잠재적 결과(<span class="math inline">\(Y(0), Y(1)\)</span>)와 무관해질 것이라고 가정하는 것이 바로 조건부 교환가능성이다.</p>
<p>이 개념은 아래의 통계 기호로 명확하게 표현된다.</p>
<p><span class="math display">\[(Y(0), Y(1)) \perp T \mid X\]</span></p>
<p>이는 <strong>’교란변수</strong> <span class="math inline">\(X\)</span>(예: 나이)의 값을 고정하면, 잠재적 결과는 실제 받은 치료와 독립적이다’라는 우리가 통계적으로 달성하고자 하는 이상적인 상태를 의미한다.</p>
<p><strong>그렇다면 이 이상적인 상태를 현실의 데이터로 어떻게 구현할 수 있을까?</strong> 바로 이 질문에 답하기 위해, ’나이’의 효과를 통제하는 다양한 통계적 방법론들이 고안되었다.</p>
<ol type="1">
<li><p><strong>층화 분석 (Stratification):</strong> 가장 개념적으로 명확한 방법이다. 데이터를 ‘60-65세’, ‘66-70세’, ‘71-75세’ 등 여러 <strong>나이대 그룹(strata)</strong>으로 나눈다. 그리고 <strong>각 나이대 그룹 안에서만</strong> 치료 효과를 각각 계산한 뒤, 이 결과들을 종합하여 나이의 영향을 보정한 전체 평균 치료 효과를 구한다.</p></li>
<li><p><strong>회귀 모형 (Regression):</strong> 가장 널리 쓰이는 방법이다. <code>결과 ~ 치료법 + 나이</code> 와 같은 회귀 모델을 사용하면, 모델이 수학적으로 <strong>’나이’가 결과에 미치는 영향을 분리하여 계산</strong>해준다. 따라서 우리가 얻는 치료법의 효과는 이미 ‘나이가 동일하다는 조건 하에서의’ 순수한 효과가 된다.</p></li>
<li><p><strong>매칭 (Matching):</strong> 가장 직관적인 방법 중 하나다. 예를 들어, <strong>72세인 수술 환자</strong> 한 명을 찾고, 데이터 안에서 <strong>똑같이 72세인 약물치료 환자</strong>를 찾아 1대1로 짝을 지어준다. 이 과정을 반복하여 나이가 똑같은 환자들로만 구성된 새로운 데이터셋을 만들어 비교한다. 교란변수가 많아지면 모든 변수가 똑같은 짝을 찾기 어려워지므로, 이를 요약한 <strong>성향점수(Propensity Score)</strong>를 기준으로 매칭하는 더 정교한 방법이 사용된다.</p></li>
</ol>
<p>이처럼 층화, 회귀, 매칭 등 각 방법의 구체적인 기술은 다르지만, 이들 모두는 ‘나이’(<span class="math inline">\(X\)</span>)라는 교란변수의 영향을 어떻게든 통제하여 <strong>조건부 교환가능성</strong>이라는 단 하나의 대원칙을 만족시키려는 동일한 목표를 가진 도구들이다.</p>
<section id="r-예제-코드-교란-효과-시뮬레이션" class="level3">
<h3 class="anchored" data-anchor-id="r-예제-코드-교란-효과-시뮬레이션">R 예제 코드: 교란 효과 시뮬레이션</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">40</span>, <span class="dv">80</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>prob_med <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(<span class="fl">0.1</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">60</span>))))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, prob_med)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>treatment_fct <span class="ot">&lt;-</span> <span class="fu">factor</span>(treatment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Surgery"</span>, <span class="st">"Medication"</span>))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>prob_death <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(<span class="sc">-</span><span class="dv">6</span> <span class="sc">+</span> <span class="fl">0.08</span> <span class="sc">*</span> age)))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>outcome_death <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, prob_death)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> age,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> treatment_fct,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">death =</span> outcome_death</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- Descriptive Statistics by Group ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Descriptive Statistics by Group ---</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_age =</span> <span class="fu">mean</span>(age),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">death_rate =</span> <span class="fu">mean</span>(death)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  treatment      N mean_age death_rate
  &lt;fct&gt;      &lt;int&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1 Surgery     4977     54.4      0.192
2 Medication  5023     65.5      0.347</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model_crude <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> treatment, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>crude_or <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_crude)[<span class="st">"treatmentMedication"</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>crude_ci <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(model_crude)[<span class="st">"treatmentMedication"</span>, ])</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>model_adjusted <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> treatment <span class="sc">+</span> age, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>adjusted_or <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_adjusted)[<span class="st">"treatmentMedication"</span>])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>adjusted_ci <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(model_adjusted)[<span class="st">"treatmentMedication"</span>, ])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- Comparison of Odds Ratios (with 95% CI) ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Comparison of Odds Ratios (with 95% CI) ---</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"Crude Odds Ratio: "</span>, <span class="fu">round</span>(crude_or, <span class="dv">2</span>), </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" (95% CI: "</span>, <span class="fu">round</span>(crude_ci[<span class="dv">1</span>], <span class="dv">2</span>), <span class="st">" - "</span>, <span class="fu">round</span>(crude_ci[<span class="dv">2</span>], <span class="dv">2</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Crude Odds Ratio: 2.24 (95% CI: 2.04 - 2.45)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"Age-Adjusted Odds Ratio: "</span>, <span class="fu">round</span>(adjusted_or, <span class="dv">2</span>), </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" (95% CI: "</span>, <span class="fu">round</span>(adjusted_ci[<span class="dv">1</span>], <span class="dv">2</span>), <span class="st">" - "</span>, <span class="fu">round</span>(adjusted_ci[<span class="dv">2</span>], <span class="dv">2</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Age-Adjusted Odds Ratio: 1.05 (95% CI: 0.95 - 1.17)</code></pre>
</div>
</div>
<p>시뮬레이션 데이터의 그룹별 특성을 먼저 살펴보면, 약물치료 그룹의 평균 연령(약 65세)이 수술 그룹(약 55세)보다 약 10세 더 높고, 그에 따라 사망률 역시 현저히 높은 것을 확인할 수 있다. 이 데이터만으로 로지스틱 회귀 분석을 수행했을 때, 수술 대비 약물치료의 오즈비는 2.24로 높게 나타난다는 것을 알 수 있다. 95% 신뢰구간이 1을 훌쩍 넘어서므로, 이 결과만 보면 약물치료가 통계적으로 유의하게 사망 위험을 2배 이상 높이는 것처럼 해석된다. 하지만 이것은 ‘나이’라는 교란변수가 만들어낸 결과라는 것을 알 수 있다. 모델에 ’나이’ 변수를 추가하여 그 효과를 통계적으로 보정한 결과, <strong>나이-보정 오즈비(Age-Adjusted Odds Ratio)는 1.05 (95% 신뢰구간: 0.95 - 1.17)</strong>로 극적으로 감소한다. 이는 통계적으로 두 치료법 간에 유의미한 사망 위험 차이가 없다는 뜻이며, ’두 치료법의 실제 효과는 동일하다’는 우리가 시뮬레이션에 설정한 진실을 정확하게 반영한다. 이처럼 교란변수 보정은 잘못된 결론을 바로잡고, 신뢰구간과 함께 결과의 불확실성을 평가함으로써 우리가 더 진실에 가까운 인과적 추론을 하도록 돕는다는 것을 알 수 있다.</p>
</section>
</section>
<section id="미측정-교란변수의-한계" class="level2">
<h2 class="anchored" data-anchor-id="미측정-교란변수의-한계">4. 미측정 교란변수의 한계</h2>
<p>’나이’처럼 우리가 측정할 수 있는 교란변수 X를 모두 통계적으로 보정했다 하더라도, 관찰 연구의 문제는 끝나지 않는다. 바로 <strong>미측정 교란변수(unmeasured confounders)</strong>의 존재 가능성이다.</p>
<p>예를 들어, 환자의 <strong>‘가정 환경 및 사회경제적 수준(SES)’</strong>이라는 변수가 있다고 가정해보자. 이 변수는 보통 병원의 데이터베이스에는 기록되지 않아 측정하기 어렵다. 하지만 SES는 다음과 같이 치료 선택과 결과 모두에 영향을 미칠 수 있다.</p>
<p>SES와 치료 선택: 경제적으로 어려운 환자는 수술 후 회복 기간 동안 일을 쉬기 어려워, 회복이 빠른 약물치료를 선호할 수 있다.</p>
<p>SES와 결과: 낮은 SES는 평소 영양 상태나 건강 정보에 대한 접근성이 낮아 기저 건강 상태가 좋지 않을 수 있으며, 이는 치료법과 무관하게 사망 위험을 높일 수 있다.</p>
<p>이 경우 SES는 ’나이’와 마찬가지로 교란변수 역할을 하지만, 데이터에 없기 때문에 우리는 ’SES가 낮은 그룹’으로 조건을 걸어 비교하는 것이 불가능하다. 결국 SES로 인한 편향이 제거되지 않은 채 결과에 반영되고, 연구자는 SES의 효과를 약물치료의 효과로 잘못 해석할 위험에 처한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">40</span>, <span class="dv">80</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ses <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>prob_med <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(<span class="fl">0.1</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">-</span>  ses)))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, prob_med)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>treatment_fct <span class="ot">&lt;-</span> <span class="fu">factor</span>(treatment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Surgery"</span>, <span class="st">"Medication"</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>prob_death <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(<span class="sc">-</span><span class="dv">6</span> <span class="sc">+</span> <span class="fl">0.08</span> <span class="sc">*</span> age <span class="sc">-</span> <span class="fl">0.7</span> <span class="sc">*</span> ses)))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>outcome_death <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, prob_death)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> age,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">ses =</span> ses, </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> treatment_fct,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">death =</span> outcome_death</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>model_crude <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> treatment, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>crude_or <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_crude)[<span class="st">"treatmentMedication"</span>])</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>crude_ci <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(model_crude)[<span class="st">"treatmentMedication"</span>, ])</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>model_adjusted_age_only <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> treatment <span class="sc">+</span> age, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>adjusted_or_age_only <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_adjusted_age_only)[<span class="st">"treatmentMedication"</span>])</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>adjusted_ci_age_only <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(model_adjusted_age_only)[<span class="st">"treatmentMedication"</span>, ])</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>model_fully_adjusted <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> treatment <span class="sc">+</span> age <span class="sc">+</span> ses, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>fully_adjusted_or <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_fully_adjusted)[<span class="st">"treatmentMedication"</span>])</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>fully_adjusted_ci <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(model_fully_adjusted)[<span class="st">"treatmentMedication"</span>, ])</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- Comparison of Odds Ratios (with Unmeasured Confounding) ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Comparison of Odds Ratios (with Unmeasured Confounding) ---</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"1. Crude Odds Ratio: "</span>, <span class="fu">round</span>(crude_or, <span class="dv">2</span>), </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" (95% CI: "</span>, <span class="fu">round</span>(crude_ci[<span class="dv">1</span>], <span class="dv">2</span>), <span class="st">" - "</span>, <span class="fu">round</span>(crude_ci[<span class="dv">2</span>], <span class="dv">2</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Crude Odds Ratio: 2.31 (95% CI: 2.09 - 2.55)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"2. Age-Adjusted Odds Ratio (Researcher's View): "</span>, <span class="fu">round</span>(adjusted_or_age_only, <span class="dv">2</span>), </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" (95% CI: "</span>, <span class="fu">round</span>(adjusted_ci_age_only[<span class="dv">1</span>], <span class="dv">2</span>), <span class="st">" - "</span>, <span class="fu">round</span>(adjusted_ci_age_only[<span class="dv">2</span>], <span class="dv">2</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2. Age-Adjusted Odds Ratio (Researcher's View): 1.13 (95% CI: 1.01 - 1.26)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"3. Fully Adjusted Odds Ratio (God's View): "</span>, <span class="fu">round</span>(fully_adjusted_or, <span class="dv">2</span>), </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" (95% CI: "</span>, <span class="fu">round</span>(fully_adjusted_ci[<span class="dv">1</span>], <span class="dv">2</span>), <span class="st">" - "</span>, <span class="fu">round</span>(fully_adjusted_ci[<span class="dv">2</span>], <span class="dv">2</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3. Fully Adjusted Odds Ratio (God's View): 0.96 (95% CI: 0.85 - 1.08)</code></pre>
</div>
</div>
<p>이번 시뮬레이션에서는 우리가 측정할 수 없는 교란변수 ’SES’가 존재할 때 어떤 일이 발생하는지 보여준다. 이 데이터는 ’낮은 SES’가 약물치료 선택 확률과 사망 확률을 모두 높이도록, 하지만 치료법 자체의 실제 효과는 없도록(True OR = 1.0) 설계되었다.시뮬레이션 결과에서 살펴볼수 있듯이, ses라는 변수를 우리가 모르는 경우에 나이라는 알고 있는 변수를 보정하더라도 오즈비를 1.18로 해석하여 위험비를 실제 값인 1과 다르게 해석하여 통계적으로 유의미하게 잘못된 결론을 내리게 된다는 것을 알 수 있다. 따라서 우리가 아는 교란변수를 정교하게 보정하더라도, <strong>데이터에 없는 중요한 교란변수가 있는 경우 추정치가 진실에서 벗어난 편향된 값</strong>을 갖게 된다는 것을 알 수 있다.</p>
<p>이것이 관찰 연구의 근본적인 한계이며, RCT가 Gold Standard인 이유이다. RCT에서는 무작위 배정을 통해 부유한 사람이든, 어려운 환경의 사람이든 모두가 수술군과 약물군에 확률적으로 고르게 분포하게 된다. 따라서 RCT는 우리가 사전에 인지하고 측정한 변수뿐만 아니라, 인지하지 못했거나 측정하지 못한 미지의 교란변수(SES, 유전적 특성, 성격 등)까지도 통계적으로 통제해준다. 하지만 RWD를 활용하는 관찰 연구에서는 이러한 완벽한 보장을 할 수 없으므로, 알려진 교란변수를 최대한 보정하여 최선의 추정치를 찾아내고자 노력하는 것이다. 5. 결론: 이상, 현실, 그리고 나아갈 길 본 글에서는 의학 연구에서 ’어떤 치료법이 더 나은가’라는 질문에 답하기 위한 인과추론의 여정을 살펴보았다. 우리는 한 개인에게 두 가지 치료법의 결과를 동시에 관찰할 수 없다는 <strong>‘인과추론의 근본적인 문제’</strong>에서 출발했다. 이로 인해 한 개인에 대한 진정한 인과적 효과(Y(1)−Y(0))는 이상적인 개념으로만 남을 뿐, 직접 계산하는 것은 불가능하다.</p>
<p>이러한 한계에 직면하여, 연구자들은 실용적인 대안으로 목표를 전환한다. 바로 개인의 효과가 아닌, 집단 전체에 대한 <strong>‘평균 인과 효과(ATE)’</strong>를 추정하는 것이다. 이는 특정 치료법이 인구 집단에 평균적으로 미치는 영향을 평가하는 강력하고 유용한 지표가 되며, 임상 현장과 보건 정책 수립에 중요한 과학적 근거를 제공한다.</p>
<p>이 ATE를 추정하는 가장 신뢰도 높은 Gold Standard는 RCT이다. RCT는 무작위 배정이라는 강력한 장치를 통해 측정 가능 여부와 상관없이 모든 교란변수의 영향을 원천적으로 차단한다. 그 결과, 치료군과 대조군은 완벽히 교환가능해지며, 두 집단의 단순 결과 비교만으로도 ATE의 불편향 추정치를 얻을 수 있다.</p>
<p>하지만 현실적인 제약으로 RCT 수행이 어려울 때, 우리는 차선책으로 RWD를 활용한 관찰 연구에 의존하게 된다. 관찰 연구에서는 무작위 배정이 없으므로, 연구자가 직접 교란변수 문제를 해결해야 한다. 우리는 ‘나이’와 같이 알려진 교란변수(X)를 통계적으로 보정함으로써, X의 특정 값 안에서는 두 집단이 교환 가능하다는 ’조건부 교환가능성’ 가정을 만족시키고자 노력한다.</p>
<p>그러나 이 접근법은 우리가 측정하지 못했거나, 존재 자체를 모르는 ‘미측정 교란변수’ 앞에서는 한계를 가진다. 관찰 연구의 신뢰성은 ’중요한 미측정 교란변수가 없다’는 강력하고 증명 불가능한 가정에 의존하게 되는 것이다. 결론적으로, RWD를 이용한 인과추론은 불완전한 데이터 속에서 RCT의 이상적인 상황을 최대한 흉내 내어, 여러 편향들을 제거하고 참값에 근접해가는 과정이라 할 수 있다.</p>
</section>
<section id="시간축관련-편향-time-related-biases" class="level2">
<h2 class="anchored" data-anchor-id="시간축관련-편향-time-related-biases">5. 시간축관련 편향 (Time-related Biases)</h2>
<p>지금까지 우리는 ’누구를 비교할 것인가’에 대한 문제, 즉 <strong>교란(Confounding)</strong>에 대해 집중적으로 살펴보았다. 이는 RWD 인과추론의 가장 중요하고 핵심적인 도전이다. 하지만 RWD 연구의 복잡성은 여기서 그치지 않는다. 교란만큼이나 치명적일 수 있는 두 번째 도전 과제가 남아있기 때문이다. 바로 “언제부터를 연구의 시작점(Time-zero)으로 볼 것인가?” 라는 시간축 설정의 문제이다.</p>
<p>RCT에서는 모든 것이 명확하다. 환자가 연구에 동의하고 무작위 배정되는 그 순간이 모든 추적 관찰의 시작점(Time-zero)이 된다. 환자 등록(Eligibility, E), 연구 시작(Time-zero, T0), 치료 배정(Assignment, A)이 한 지점에서 동시에 일어난다. 하지만 RWD에서는 이 세 가지 시점이 각기 다르게 흩어져 있는 경우가 대부분이며, 이를 잘못 정렬할 경우 연구 결과가 완전히 왜곡될 수 있다. 실제 유명 연구 사례와 간단한 시뮬레이션을 통해 그 위험성을 살펴보자.</p>
<p>5.1 사례: 불멸 시간 편향 (Immortal Time Bias)과 호르몬 대체 요법(HRT) 과거 여러 관찰 연구에서는 폐경 후 여성을 대상으로 한 호르몬 대체 요법(HRT)이 심혈관 질환 위험을 크게 낮춘다(RR ≈ 0.6)고 보고했다. 하지만 이후 진행된 대규모 RCT(WHI Trial)에서는 정반대로 HRT가 오히려 위험을 약간 높인다(HR ≈ 1.2)는 결과가 나왔다. 이 차이는 어디서 발생한 것일까?</p>
<p>이러한 불일치는 관찰 연구에서 추적 관찰의 시작점(Time-zero)을 정의하고 정렬하는 과정에서 발생하는 체계적 오류에서 비롯된다. RCT에서는 연구 참여 자격 판별(Eligibility, E), 추적 관찰 시작(Time-zero, T0), 치료법 배정(Assignment, A)이 ’무작위 배정’이라는 단일한 시점에 동시에 일어나 모든 참가자가 동일한 출발선에 선다.</p>
<p>반면, 실제 진료 데이터(RWD)에서는 이 세 시점이 분산된다. 예를 들어, 한 여성이 폐경을 맞아 HRT 처방 자격(E)을 얻는 시점과, 의사가 실제로 HRT를 처방하여 치료가 배정(A)되는 시점 사이에는 수개월에서 수년의 시간적 간극이 발생한다. 이 시간적 간극은 체계적인 선택 편향(Selection Bias)을 유발하는 기전으로 작용한다.</p>
<p>‘HRT 사용자’로 분류되기 위해서는, 환자는 처방 자격을 얻은 뒤(E) 치료를 실제로 배정받을 때까지(A) 해당 연구의 관심 결과(outcome) 없이 생존해야만 한다. 이 생존이 조건이 되는 기간이 바로 <strong>’불멸의 시간(Immortal Time)’</strong>이다. 이 기간에 사망하거나 관심 결과가 발생한 환자는 정의상 ’HRT 사용자’ 그룹에 포함될 수 없다. 결과적으로 ‘HRT 사용자’ 그룹은 이 생존 기간을 통과한, 상대적으로 건강한 개인들로 구성될 수밖에 없다.</p>
<p>이로 인해 분석가는 ’건강한 사용자 편향(Healthy User Bias)’에 직면한다. 즉, 치료 그룹의 낮은 위험은 약물의 실제 효과가 아니라, 치료를 받기 이전부터 해당 그룹이 가지고 있던 기저의 건강상태 때문일 가능성이 높다.</p>
<p>이는 분석가에게 Time-zero 설정의 딜레마를 안겨준다. 만약 치료 배정 시점(A)을 Time-zero로 설정하면, ‘불멸의 시간’ 동안의 생존자만 포함하게 되어 앞서 언급한 선택 편향을 피할 수 없다. 반대로 모든 환자의 자격 획득 시점(E)을 Time-zero로 설정한다면, 시간에 따라 치료 여부가 변하는 변수(Time-varying Covariate)를 통계적으로 정교하게 처리해야 하는 복잡성에 직면한다. 관찰 연구에서 E, T0, A를 개념적으로 명확히 정렬하는 것의 어려움이 바로 Immortal Time Bias가 발생하는 근본적인 원인이다.</p>
<p>R 시뮬레이션: 불멸 시간 편향의 재현 HRT의 실제 효과가 전혀 없다고(True HR = 1.0) 가정하고, 단지 치료 시작 시점만 환자마다 다른 상황을 시뮬레이션한다. 분석 과정에서 ’치료 시작 전에 사망한 환자’를 제외하는, 실제 연구에서 발생했던 오류를 그대로 재현해 본다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jstable)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. RCT처럼 치료군과 대조군을 1:1로 무작위 배정한다.</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>group <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. '초기 위험'이 높은 Weibull 분포로 생존 시간을 생성한다.</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># shape &lt; 1 (e.g., 0.7)은 초기에 사망 위험(hazard)이 가장 높고,</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 시간이 지남에 따라 위험이 감소하는 것을 의미한다.</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 두 그룹의 근본적인 생존 분포는 완전히 동일하다.</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>death_time <span class="ot">&lt;-</span> <span class="fu">rweibull</span>(n, <span class="at">shape =</span> <span class="fl">0.7</span>, <span class="at">scale =</span> <span class="dv">10</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. 치료군(group=1)에만 치료 시작 시간을 무작위로 부여한다.</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 치료 시작은 위험이 높은 초기 구간(e.g., 0 ~ 2.5) 내에서 이루어진다고 가정한다.</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>tx_start_time <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>tx_start_time[group <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">sum</span>(group <span class="sc">==</span> <span class="dv">1</span>), <span class="dv">0</span>, <span class="fl">2.5</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>df_base <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> group,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">death_time =</span> death_time,</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">tx_start_time =</span> tx_start_time,</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">event =</span> <span class="dv">1</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. 잘못된 분석 데이터셋을 구축한다.</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="co"># 4-1. 대조군(group=0) 데이터: Time-zero는 배정 시점(0)이다.</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>df_control <span class="ot">&lt;-</span> df_base <span class="sc">%&gt;%</span> </span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fup_time =</span> death_time)</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="co"># 4-2. 치료군(group=1) 데이터: 잘못된 분석 적용</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>df_treated_biased <span class="ot">&lt;-</span> df_base <span class="sc">%&gt;%</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 오류 (a): "초기 위험 구간"에서의 사망자 제외 (Immortal Time)</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(death_time <span class="sc">&gt;=</span> tx_start_time) <span class="sc">%&gt;%</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 오류 (b): 치료 시작 시점을 새로운 Time-zero로 설정</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fup_time =</span> death_time <span class="sc">-</span> tx_start_time)</span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="co"># 4-3. 두 데이터셋을 합친다.</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>df_final_biased <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>  df_control,</span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>  df_treated_biased</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group_fct =</span> <span class="fu">factor</span>(group, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)))</span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. 편향이 발생한 모델을 분석한다.</span></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>biased_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(fup_time, event) <span class="sc">~</span> group_fct, <span class="at">data =</span> df_final_biased, <span class="at">model =</span> T)</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- Biased Analysis with Early High-Risk &amp; Flawed Design ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Biased Analysis with Early High-Risk &amp; Flawed Design ---</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cox2.display</span>(biased_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
                                HR(95%CI)          P value  
group_fct: Treatment vs Control "0.87 (0.84,0.91)" "&lt; 0.001"

$metric
                        [,1] [,2]
&lt;NA&gt;                      NA   NA
No. of observations   9009.0   NA
No. of events         9009.0   NA
AIC                 146024.3   NA

$caption
[1] "Cox model on time ('fup_time') to event ('event')"</code></pre>
</div>
</div>
<p>코드 해석: 위 시뮬레이션에서는 치료(HRT)가 생존에 아무런 영향을 주지 않도록 설계했다. 하지만 filter() 구문을 통해 ‘치료를 받기 전에 사망한 환자’를 분석에서 제외하는 오류를 적용하자, ’Ever Treated’ 그룹의 Hazard Ratio(exp(coef))는 약 0.73으로 나타난다.</p>
<p>이는 치료를 받은 그룹의 사망 위험이 27%나 낮은 것처럼 보이는 심각한 편향이다. 이 결과는 약물의 효과가 아니라, 단지 ‘Ever Treated’ 그룹이 치료를 받기 위해 생존해야 했던 ’불멸의 시간’이라는 관문을 통과한, 선천적으로 더 건강한 집단이었기 때문에 발생한 착시 현상이다. 이처럼 시간축을 잘못 설정하는 것은 결국 비교 집단의 근본적인 특성을 왜곡하여 인과추론을 불가능하게 만든다.</p>
<p>5.2 사례: 기존 사용자 편향 (Prevalent User Bias)과 스타틴(Statin) 스타틴의 심혈관 질환 예방 효과를 다룬 한 유명 관찰 연구에서는 스타틴이 사망 위험을 유의미하게 낮춘다(HR 0.85)고 보고했지만, 이 역시 여러 RCT의 메타분석 결과(HR 1.00)와는 상반된 결과였다.</p>
<p>이 편향의 원인은 <strong>‘기존 사용자(Prevalent User)’</strong>를 연구에 포함했기 때문이다. 연구 시작 시점에 이미 스타틴을 오랫동안 복용해 온 환자들은 약물의 초기 부작용이나 안 좋은 효과를 이미 ‘통과하고 살아남은’ 건강한 환자들일 가능성이 높다. 약물에 잘 적응하지 못했거나 초기에 부작용을 겪은 환자들은 이미 복용을 중단했을 것이다. 이처럼 ‘선택된 생존자’ 그룹을 약물을 처음 사용하는 그룹(New User)과 비교하면, 약물의 안전성이나 효과가 실제보다 과대평가될 수밖에 없다.</p>
<p>R 시뮬레이션: 기존 사용자 편향의 재현 스타틴에 ‘민감한(susceptible)’ 환자 그룹과 ‘강건한(robust)’ 환자 그룹이 있다고 가정하고, 민감한 그룹은 초기에 탈락할 확률이 높다고 시뮬레이션해보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>susceptible <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.2</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>prob_dropout <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(susceptible <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.05</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>washin_survivor <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="dv">1</span> <span class="sc">-</span> prob_dropout)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>df_prevalent <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n, <span class="at">susceptible =</span> susceptible) <span class="sc">|&gt;</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(washin_survivor <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">id =</span> (n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n), <span class="at">susceptible =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.2</span>))</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>prob_death_future <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_prevalent<span class="sc">$</span>susceptible <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.2</span>, <span class="fl">0.05</span>)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>prevalent_death_rate <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="fu">nrow</span>(df_prevalent), <span class="dv">1</span>, prob_death_future))</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>prob_death_future_new <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_new<span class="sc">$</span>susceptible <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.2</span>, <span class="fl">0.05</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>new_user_death_rate <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="fu">nrow</span>(df_new), <span class="dv">1</span>, prob_death_future_new))</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- Bias from Prevalent Users ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Bias from Prevalent Users ---</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(<span class="st">"Death Rate among Prevalent Users:"</span>, <span class="fu">round</span>(prevalent_death_rate, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Death Rate among Prevalent Users: 0.066 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(<span class="st">"Death Rate among New Users:"</span>, <span class="fu">round</span>(new_user_death_rate, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Death Rate among New Users: 0.083 </code></pre>
</div>
</div>
<p>코드 해석: 시뮬레이션 결과, <strong>기존 사용자 그룹의 사망률(약 5.9%)</strong>이 <strong>신규 사용자 그룹의 사망률(약 7.8%)</strong>보다 현저히 낮게 나타난다. 이는 약물이 장기적으로 더 효과적이어서가 아니라, 기존 사용자 그룹에는 약물에 취약했던 ‘민감한’ 환자들이 초기에 이미 걸러졌기 때문이다. 이처럼 약물 사용 경험이 다른 두 그룹을 직접 비교하면, 우리는 약물의 효과를 심각하게 오인할 수 있다.</p>
<p>결론: 두 가지 도전을 넘어 결론적으로, RWD를 이용한 인과추론은 ’사과와 오렌지를 비교’하는 <strong>교란(Confounding)</strong>의 문제와, ’출발선이 다른 달리기 경주’를 보는 듯한 <strong>시간축 설정(Time-related biases)</strong>의 문제라는 두 가지 큰 도전에 직면한다.</p>
<p>지금까지 우리는 이 두 가지 도전이 왜 발생하며 연구 결과를 얼마나 심각하게 왜곡할 수 있는지 실제 사례와 코드를 통해 살펴보았다. 다음 파트부터는 이 두 가지 도전을 하나씩 정복해 나갈 것이다.</p>
<p>먼저 Part 2에서는 ‘교란’ 문제를 해결하기 위한 다양한 통계 및 머신러닝 기법들을 심도 있게 다룰 것이다. 그리고 <strong>Part 3에서는 오늘 소개한 ’시간의 함정’들을 피하기 위한 연구 설계와 표적 시험 모방(Target Trial Emulation)</strong>과 같은 고급 분석 전략에 대해 알아볼 예정이다. 이 여정을 통해 우리는 불완전한 데이터 속에서 어떻게 더 신뢰도 높은 인과적 추론을 할 수 있는지에 대한 통찰을 얻게 될 것이다.</p>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{jo2025,
  author = {Jo, Hyungwoo},
  title = {Causal {Inference} (1)},
  date = {2025-06-27},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-jo2025" class="csl-entry quarto-appendix-citeas" role="listitem">
Jo, Hyungwoo. 2025. <span>“Causal Inference (1).”</span> June 27, 2025.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>